spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  jwt:
    secret: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"

logging:
  level:
    org.elasticsearch.client: TRACE

feign:
  user:
    url: http://test-dummy
