spring:
  application:
    name: search-service

  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: ${SPRING_ELASTIC_SEARCH_URL}

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}
  repository-uri: ${SENTRY_REPOSITORY_URI}

logging:
  config: classpath:logback-spring.xml

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}
