# 주석 추가
server:
  forward-headers-strategy: framework  # ALB HTTPS 헤더 인식

spring:
  application:
    name: search-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5s
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: 3s

    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: ${SPRING_ELASTIC_SEARCH_URL}
    index : ${SPRING_ELASTIC_SEARCH_INDEX}

  jwt:
    secret: ${JWT_SECRET}

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}
  repository-uri: ${SENTRY_REPOSITORY_URI}

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    ads.client: debug
    com.client.external: debug
    com.playus.searchservice.domain.common.feign.client: DEBUG

feign:
  user:
    url: ${FEIGN_USER_URL}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      circuit:
        base-config: default

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}

management:
  endpoints:
    web:
      exposure:
        include:
          - health           # 애플리케이션 상태 확인
          - info
          - prometheus       # 메트릭 데이터 노출
          - metrics          # 메트릭 엔드포인트 추가
          - tracing          # 트레이싱 엔드포인트 추가

  # 트레이싱 설정
  tracing:
    sampling:
      probability: 1.0  # 개발환경 100% 샘플링

  endpoint:
    health:
      show-details: always  # 모니터링을 위해 상세 정보 표시

  # 메트릭에 기본 태그 추가
  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev
